name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Configure Git
      run: |
        git config --global --add safe.directory /home/runner/work/${{ github.repository }}
        git config --global --unset-all core.sshCommand || true
        git config --global --unset-all http.https://github.com/.extraheader || true
    - name: List files
      run: ls -la
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
