name: Compilar C no Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Listar arquivos no diretório
        run: dir  # Verifica se o arquivo 'configure' está presente

      - name: Instalar MSYS2 e Autotools
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make
            autoconf
            automake
            libtool

      - name: Rodar ./configure com MSYS2
        shell: msys2 {0}
        run: ./configure

      - name: Compilar código
        shell: msys2 {0}
        run: make

      - name: Testar código
        shell: msys2 {0}
        run: make check
