
name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar
        run: ./configure

      - name: Compilar
        run: make

      - name: Testar
        run: make check

      - name: Verificação final
        run: make distcheck
